-- MySQL Script generated by MySQL Workbench
-- 01/26/16 14:36:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kadabrakup
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kadabrakup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kadabrakup` DEFAULT CHARACTER SET latin1 ;
USE `kadabrakup` ;

-- -----------------------------------------------------
-- Table `kadabrakup`.`arquivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kadabrakup`.`arquivos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idPasta` INT(11) NULL DEFAULT NULL COMMENT '',
  `caminhoArquivo` TEXT NULL DEFAULT NULL COMMENT '',
  `timestamp` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 21995
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `kadabrakup`.`computador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kadabrakup`.`computador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `destino` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `status` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `heavy` TINYINT(4) NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `kadabrakup`.`copiarpasta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kadabrakup`.`copiarpasta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idComputador` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `enderecoPasta` VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `kadabrakup`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kadabrakup`.`logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idComputador` INT(11) NULL DEFAULT NULL COMMENT '',
  `mensagem` TEXT NULL DEFAULT NULL COMMENT '',
  `data` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2387
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
